<a href="https://colab.research.google.com/github/numanbutt27/ML-ASSIGNMENT-1/blob/main/ML_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
#PART 1
#By using For Loop
myarray=np.random.normal(size=(300,2));
arr=[];
for i in range(len(myarray)):
  for j in range(len(myarray[i])):
    dist=((myarray[i,0]-myarray[j,0])**2+(myarray[i,1]-myarray[j,1])**2)**0.5;
print(dist);
arr.append(dist);
print("-------------------");
#PART 2
#By using Vactorization
x = np.random.normal(size=(300,2))
from scipy.spatial import distance_matrix
dist1=distance_matrix(x,x);
print(dist1);
#PART 3
print("Time Complexity For Vactorization:");
%timeit dist1;
print("Time Complexity For Loops:");
%timeit arr.append(dist);




3.028323309741634
-------------------
[[0.         2.57050436 3.43018831 ... 3.34140655 1.28869624 2.39635016]
 [2.57050436 0.         0.89317617 ... 0.86726595 2.13955102 2.2158694 ]
 [3.43018831 0.89317617 0.         ... 0.20337725 2.81422969 2.55837612]
 ...
 [3.34140655 0.86726595 0.20337725 ... 0.         2.66553399 2.36616314]
 [1.28869624 2.13955102 2.81422969 ... 2.66553399 0.         1.1122625 ]
 [2.39635016 2.2158694  2.55837612 ... 2.36616314 1.1122625  0.        ]]
Time Complexity For Vactorization:

40.1 ns ± 5.66 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
Time Complexity For Loops:
109 ns ± 6.14 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
